### PR TITLE
Update dummy rails

### PR DESCRIPTION
**Pull request by riseshia**
This patch is:

- Solve security vulnerabilities notice given from github.

#10 is required to pass test.
and travis ci for ruby 2.1 is failing. ;)
How do we handle this?

Could you review this? @cookpad/dev-infra @k0kubun

### CODE REVIEW

**Comment by eagletmt** [comment]
Don't mix behavior changes with other changes.

**Comment by riseshia** [comment]
> Don't mix behavior changes with other changes.

Sorry, I split patch for rails 5 to #10

**Comment by riseshia** [comment]
rebased

**Comment by hogelog** [comment]
ruby 2.1.10 failed https://travis-ci.org/cookpad/barbeque_client/jobs/316714319

Rails 5 requires Ruby 2.2.2+.

**Comment by riseshia** [comment]
🙈

- Just leave this
- Allow fail at 2.1.10
- Allow fail at 2.1.10 with rails 5 (It may need 2 dummy project..?)

**Comment by eagletmt** [comment]
let's remove Ruby 2.1 from supported Ruby versions

**Comment by riseshia** [comment]
Dropped 2.1.x support b7f71da

**Review by hogelog — APPROVED** [review]

**Pull request merged**
